# fly.toml app configuration file generated for image-converter-thrumming-snow-4824 on 2025-02-01T13:55:40+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'image-converter-thrumming-snow-4824'
primary_region = 'fra'

[build]

[http_service]
  internal_port = 3001
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
